// Data này fake để sài tạm, mốt thay bằng api

export const testData = [
  {
    id: '01',
    stt: '1',
    cauhoi: 'Javascript',
    a: '2021-06-20',
    b: '19:00',
    c: 'Cau cccccccccc saf',
    d: 'Kiểm tra 90 phút',
    dachon: 'C',
    status: '2',
  },
  {
    id: '02',
    stt: '2',
    cauhoi: 'Lập trình web',
    a: '2021-06-20',
    b: '13:30',
    c: 'Cau cccccccccc saf',
    d: 'Kiểm tra 1 tiết',
    dachon: 'A',
    status: '1',
  },
  {
    id: '03',
    stt: '3',
    cauhoi: 'Lập trình nhúng',
    a: '2021-06-15',
    b: '19:00',
    dachon: '',
    status: '1',
    c: 'Cau cccccccccc saf',
    d: 'Kiểm tra 1 tiết',
  },
  {
    id: '04',
    stt: '4',
    cauhoi: 'Javascript',
    a: '2021-06-15',
    b: '19:00',
    c: 'Cau cccccccccc saf',
    d: 'Kiểm tra hệ số 2',
    dachon: 'C',
    status: '1',
  },
  {
    id: '05',
    stt: '5',
    cauhoi: 'Database',
    a: '2021-06-16',
    b: '19:00',
    c: 'Cau cccccccccc saf',
    d: 'Kiểm tra lần 1',
    dachon: 'A',
    status: '0',
  },
  {
    id: '06',
    stt: '6',
    cauhoi: 'Database nâng cao',
    a: '2021-06-13',
    b: '19:00',
    c: 'Cau cccccccccc saf',
    d: 'Kiểm tra lần 1',
    dachon: 'C',
    status: '2',
  },
  {
    id: '07',
    stt: '7',
    cauhoi: 'Database nâng cao',
    a: '2021-06-18',
    b: '19:00',
    c: 'Cau cccccccccc saf',
    d: 'Kiểm tra lần 1',
    dachon: 'B',
    status: '1',
  },
  {
    id: '08',
    stt: '8',
    cauhoi: 'Javascript nâng cao',
    a: '2021-06-15',
    b: '19:00',
    c: 'Cau cccccccccc saf',
    d: 'Kiểm tra hệ số 2',
    dachon: 'C',
    status: '2',
  },
  {
    id: '09',
    stt: '9',
    cauhoi: 'Javascript nâng cao hơn chút xíu',
    a: '2021-06-15',
    b: '19:00',
    c: 'Cau cccccccccc saf',
    d: 'Kiểm tra hệ số 9',
    dachon: 'C',
    status: '1',
  },
  {
    id: '10',
    stt: '10',
    cauhoi: 'PHP cơ bản',
    a: '2021-06-15',
    b: '12:00',
    c: 'Cau cccccccccc saf',
    d: 'Kiểm tra lần 1',
    dachon: 'C',
    status: '0',
  },
  {
    id: '11',
    stt: '11',
    cauhoi: 'PHP cơ bản',
    a: '2021-06-15',
    b: '19:00',
    c: 'Cau cccccccccc saf',
    d: 'Kiểm tra lần 2',
    dachon: 'C',
    status: '1',
  },
  {
    id: '012',
    stt: '12',
    cauhoi: 'Javascript',
    a: '2021-06-20',
    b: '19:00',
    c: 'Cau cccccccccc saf',
    d: 'Kiểm tra 90 phút',
    dachon: 'D',
    status: '2',
  },
  {
    id: '13',
    stt: '13',
    cauhoi: 'Lập trình web',
    a: '2021-06-20',
    b: '13:30',
    c: 'Cau cccccccccc saf',
    d: 'Kiểm tra 1 tiết',
    dachon: '',
    status: '1',
  },
  {
    id: '14',
    stt: '14',
    cauhoi: 'Lập trình nhúng',
    a: '2021-06-15',
    b: '19:00',
    dachon: 'C',
    status: '1',
    c: 'Cau cccccccccc saf',
    d: 'Kiểm tra 1 tiết',
  },
  {
    id: '015',
    stt: '15',
    cauhoi: 'Database',
    a: '2021-06-16',
    b: '19:00',
    c: 'Cau cccccccccc saf',
    d: 'Kiểm tra lần 1',
    dachon: '',
    status: '0',
  },
  {
    id: '016',
    stt: '16',
    cauhoi: 'Database nâng cao',
    a: '2021-06-13',
    b: '19:00',
    c: 'Cau cccccccccc saf',
    d: 'Kiểm tra lần 1',
    dachon: 'C',
    status: '2',
  },
  {
    id: '017',
    stt: '17',
    cauhoi: 'Database nâng cao',
    a: '2021-06-18',
    b: '19:00',
    c: 'Cau cccccccccc saf',
    d: 'Kiểm tra lần 1',
    dachon: 'C',
    status: '1',
  },
  {
    id: '018',
    stt: '18',
    cauhoi: 'Javascript nâng cao',
    a: '2021-06-15',
    b: '19:00',
    c: 'Cau cccccccccc saf',
    d: 'Kiểm tra hệ số 2',
    dachon: 'C',
    status: '2',
  },
  {
    id: '019',
    stt: '19',
    cauhoi: 'Javascript nâng cao hơn chút xíu',
    a: '2021-06-15',
    b: '19:00',
    c: 'Cau cccccccccc saf',
    d: 'Kiểm tra hệ số 9',
    dachon: '',
    status: '1',
  },
  {
    id: '20',
    stt: '20',
    cauhoi: 'PHP cơ bản',
    a: '2021-06-15',
    b: '12:00',
    c: 'Cau cccccccccc saf',
    d: 'Kiểm tra lần 1',
    dachon: '',
    status: '0',
  },
  {
    id: '21',
    stt: '21',
    cauhoi: 'PHP cơ bản',
    a: '2021-06-15',
    b: '19:00',
    c: 'Cau cccccccccc saf',
    d: 'Kiểm tra lần 2',
    dachon: 'C',
    status: '1',
  },

  {
    id: '022',
    stt: '22',
    cauhoi: 'Lập trình web',
    a: '2021-06-20',
    b: '13:30',
    c: 'Cau cccccccccc saf',
    d: 'Kiểm tra 1 tiết',
    dachon: 'C',
    status: '1',
  },
  {
    id: '023',
    stt: '23',
    cauhoi: 'Lập trình nhúng',
    a: '2021-06-15',
    b: '19:00',
    dachon: 'C',
    status: '1',
    c: 'Cau cccccccccc saf',
    d: 'Kiểm tra 1 tiết',
  },
  {
    id: '024',
    stt: '24',
    cauhoi: 'Javascript',
    a: '2021-06-15',
    b: '19:00',
    c: 'Cau cccccccccc saf',
    d: 'Kiểm tra hệ số 2',
    dachon: 'C',
    status: '1',
  },
  {
    id: '025',
    stt: '25',
    cauhoi: 'Database',
    a: '2021-06-16',
    b: '19:00',
    c: 'Cau cccccccccc saf',
    d: 'Kiểm tra lần 1',
    dachon: '',
    status: '0',
  },
  {
    id: '026',
    stt: '26',
    cauhoi: 'Database nâng cao',
    a: '2021-06-13',
    b: '19:00',
    c: 'Cau cccccccccc saf',
    d: 'Kiểm tra lần 1',
    dachon: 'C',
    status: '2',
  },
  {
    id: '027',
    stt: '27',
    cauhoi: 'Database nâng cao',
    a: '2021-06-18',
    b: '19:00',
    c: 'Cau cccccccccc saf',
    d: 'Kiểm tra lần 1',
    dachon: 'C',
    status: '1',
  },
  {
    id: '028',
    stt: '28',
    cauhoi: 'Javascript nâng cao',
    a: '2021-06-15',
    b: '19:00',
    c: 'Cau cccccccccc saf',
    d: 'Kiểm tra hệ số 2',
    dachon: '',
    status: '2',
  },
  {
    id: '029',
    stt: '29',
    cauhoi: 'Javascript nâng cao hơn chút xíu',
    a: '2021-06-15',
    b: '19:00',
    c: 'Cau cccccccccc saf',
    d: 'Kiểm tra hệ số 9',
    dachon: 'C',
    status: '1',
  },
  {
    id: '30',
    stt: '30',
    cauhoi: 'PHP cơ bản',
    a: '2021-06-15',
    b: '12:00',
    c: 'Cau cccccccccc saf',
    d: 'Kiểm tra lần 1',
    dachon: 'C',
    status: '0',
  },
  {
    id: '31',
    stt: '31',
    cauhoi: 'PHP cơ bản',
    a: '2021-06-15',
    b: '19:00',
    c: 'Cau cccccccccc saf',
    d: 'Kiểm tra lần 2',
    dachon: 'C',
    status: '1',
  },

  {
    id: '032',
    stt: '32',
    cauhoi: 'Lập trình web',
    a: '2021-06-20',
    b: '13:30',
    c: 'Cau cccccccccc saf',
    d: 'Kiểm tra 1 tiết',
    dachon: 'C',
    status: '1',
  },
  {
    id: '033',
    stt: '33',
    cauhoi: 'Lập trình nhúng',
    a: '2021-06-15',
    b: '19:00',
    dachon: '',
    status: '1',
    c: 'Cau cccccccccc saf',
    d: 'Kiểm tra 1 tiết',
  },
  {
    id: '034',
    stt: '34',
    cauhoi: 'Javascript',
    a: '2021-06-15',
    b: '19:00',
    c: 'Cau cccccccccc saf',
    d: 'Kiểm tra hệ số 2',
    dachon: 'A',
    status: '1',
  },
  {
    id: '035',
    stt: '35',
    cauhoi: 'Database',
    a: '2021-06-16',
    b: '19:00',
    c: 'Cau cccccccccc saf',
    d: 'Kiểm tra lần 1',
    dachon: 'C',
    status: '0',
  },
  {
    id: '036',
    stt: '36',
    cauhoi: 'Database nâng cao',
    a: '2021-06-13',
    b: '19:00',
    c: 'Cau cccccccccc saf',
    d: 'Kiểm tra lần 1',
    dachon: 'C',
    status: '2',
  },
  {
    id: '037',
    stt: '37',
    cauhoi: 'Database nâng cao',
    a: '2021-06-18',
    b: '19:00',
    c: 'Cau cccccccccc saf',
    d: 'Kiểm tra lần 1',
    dachon: 'C',
    status: '1',
  },
  {
    id: '038',
    stt: '38',
    cauhoi: 'Javascript nâng cao',
    a: '2021-06-15',
    b: '19:00',
    c: 'Cau cccccccccc saf',
    d: 'Kiểm tra hệ số 2',
    dachon: 'C',
    status: '2',
  },
  {
    id: '039',
    stt: '39',
    cauhoi: 'Javascript nâng cao hơn chút xíu',
    a: '2021-06-15',
    b: '19:00',
    c: 'Cau cccccccccc saf',
    d: 'Kiểm tra hệ số 9',
    dachon: '',
    status: '1',
  },
  {
    id: '40',
    stt: '40',
    cauhoi: 'PHP cơ bản',
    a: '2021-06-15',
    b: '12:00',
    c: 'Cau cccccccccc saf',
    d: 'Kiểm tra lần 1',
    dachon: 'C',
    status: '0',
  },
  {
    id: '041',
    stt: '41',
    cauhoi: 'Javascript',
    a: '2021-06-20',
    b: '19:00',
    c: 'Cau cccccccccc saf',
    d: 'Kiểm tra 90 phút',
    dachon: 'C',
    status: '2',
  },
  {
    id: '042',
    stt: '42',
    cauhoi: 'Lập trình web',
    a: '2021-06-20',
    b: '13:30',
    c: 'Cau cccccccccc saf',
    d: 'Kiểm tra 1 tiết',
    dachon: 'C',
    status: '1',
  },
  {
    id: '043',
    stt: '43',
    cauhoi: 'Lập trình nhúng',
    a: '2021-06-15',
    b: '19:00',
    dachon: 'C',
    status: '1',
    c: 'Cau cccccccccc saf',
    d: 'Kiểm tra 1 tiết',
  },
  {
    id: '044',
    stt: '44',
    cauhoi: 'Javascript',
    a: '2021-06-15',
    b: '19:00',
    c: 'Cau cccccccccc saf',
    d: 'Kiểm tra hệ số 2',
    dachon: 'C',
    status: '1',
  },
  {
    id: '045',
    stt: '45',
    cauhoi: 'Database',
    a: '2021-06-16',
    b: '19:00',
    c: 'Cau cccccccccc saf',
    d: 'Kiểm tra lần 1',
    dachon: 'C',
    status: '0',
  },
  {
    id: '046',
    stt: '46',
    cauhoi: 'Database nâng cao',
    a: '2021-06-13',
    b: '19:00',
    c: 'Cau cccccccccc saf',
    d: 'Kiểm tra lần 1',
    dachon: 'C',
    status: '2',
  },
  {
    id: '047',
    stt: '47',
    cauhoi: 'Database nâng cao',
    a: '2021-06-18',
    b: '19:00',
    c: 'Cau cccccccccc saf',
    d: 'Kiểm tra lần 1',
    dachon: 'C',
    status: '1',
  },
  {
    id: '048',
    stt: '48',
    cauhoi: 'Javascript nâng cao',
    a: '2021-06-15',
    b: '19:00',
    c: 'Cau cccccccccc saf',
    d: 'Kiểm tra hệ số 2',
    dachon: 'C',
    status: '2',
  },
  {
    id: '049',
    stt: '49',
    cauhoi: 'Javascript nâng cao hơn chút xíu',
    a: '2021-06-15',
    b: '19:00',
    c: 'Cau cccccccccc saf',
    d: 'Kiểm tra hệ số 9',
    dachon: 'C',
    status: '1',
  },
  {
    id: '50',
    stt: '50',
    cauhoi: 'PHP cơ bản',
    a: '2021-06-15',
    b: '12:00',
    c: 'Cau cccccccccc saf',
    d: 'Kiểm tra lần 1',
    dachon: 'C',
    status: '0',
  },
  {
    id: '051',
    stt: '51',
    cauhoi: 'Javascript',
    a: '2021-06-20',
    b: '19:00',
    c: 'Cau cccccccccc saf',
    d: 'Kiểm tra 90 phút',
    dachon: 'C',
    status: '2',
  },
  {
    id: '052',
    stt: '52',
    cauhoi: 'Lập trình web',
    a: '2021-06-20',
    b: '13:30',
    c: 'Cau cccccccccc saf',
    d: 'Kiểm tra 1 tiết',
    dachon: 'C',
    status: '1',
  },
  {
    id: '053',
    stt: '53',
    cauhoi: 'Lập trình nhúng',
    a: '2021-06-15',
    b: '19:00',
    dachon: 'C',
    status: '1',
    c: 'Cau cccccccccc saf',
    d: 'Kiểm tra 1 tiết',
  },
  {
    id: '504',
    stt: '54',
    cauhoi: 'Javascript',
    a: '2021-06-15',
    b: '19:00',
    c: 'Cau cccccccccc saf',
    d: 'Kiểm tra hệ số 2',
    dachon: 'C',
    status: '1',
  },
  {
    id: '055',
    stt: '55',
    cauhoi: 'Database',
    a: '2021-06-16',
    b: '19:00',
    c: 'Cau cccccccccc saf',
    d: 'Kiểm tra lần 1',
    dachon: 'C',
    status: '0',
  },
  {
    id: '056',
    stt: '56',
    cauhoi: 'Database nâng cao',
    a: '2021-06-13',
    b: '19:00',
    c: 'Cau cccccccccc saf',
    d: 'Kiểm tra lần 1',
    dachon: 'C',
    status: '2',
  },
  {
    id: '057',
    stt: '57',
    cauhoi: 'Database nâng cao',
    a: '2021-06-18',
    b: '19:00',
    c: 'Cau cccccccccc saf',
    d: 'Kiểm tra lần 1',
    dachon: 'C',
    status: '1',
  },
  {
    id: '058',
    stt: '58',
    cauhoi: 'Javascript nâng cao',
    a: '2021-06-15',
    b: '19:00',
    c: 'Cau cccccccccc saf',
    d: 'Kiểm tra hệ số 2',
    dachon: 'C',
    status: '2',
  },
  {
    id: '059',
    stt: '59',
    cauhoi: 'Javascript nâng cao hơn chút xíu',
    a: '2021-06-15',
    b: '19:00',
    c: 'Cau cccccccccc saf',
    d: 'Kiểm tra hệ số 9',
    dachon: 'C',
    status: '1',
  },
];
