export const ITEM_KEYS = {
  MON_HOC: 'MON_HOC_KEY',
  BAI_KIEM_TRA: 'BAI_KIEM_TRA_KEY',
  DA_KET_THUC: 'DA_KET_THUC_KEY',
  SAP_DIEN_RA: 'SAP_DIEN_RA_KEY',
  CAU_HOI: 'CAU_HOI_KEY',
  CHU_DE: 'CHU_DE_KEY',
  LOP_HOC_PHAN: 'LOP_HOC_PHAN_KEY',
  ABOUT: 'ABOUT_KEY',
};
